Ext.ux.App.OrderManager.Order = new Ext.ux.MVC.model.Base('order', {
  fields: [
    { name: 'id',                                  type: 'int'},
    { name: 'email',                               type: 'string'},
    { name: 'first_name',                          type: 'string'},
    { name: 'last_name',                           type: 'string'},
    { name: 'address_1',                           type: 'string'},
    { name: 'address_2',                           type: 'string'},
    { name: 'town',                                type: 'string'},
    { name: 'county',                              type: 'string'},
    { name: 'country',                             type: 'string'},
    { name: 'postcode',                            type: 'string'},
    { name: 'phone',                               type: 'string'},
    { name: 'status',                              type: 'string'},
    { name: 'delivery_price',                      type: 'string'},
    { name: 'created_at',                          type: 'string'},
    { name: 'updated_at',                          type: 'string'},
    { name: 'delivery_address_1',                  type: 'string'},
    { name: 'delivery_address_2',                  type: 'string'},
    { name: 'delivery_address_3',                  type: 'string'},
    { name: 'delivery_town',                       type: 'string'},
    { name: 'delivery_county',                     type: 'string'},
    { name: 'delivery_postcode',                   type: 'string'},
    { name: 'billing_address_is_delivery_address', type: 'string'},
    { name: 'alternative_access',                  type: 'string'},
    { name: 'delivery_date',                       type: 'string'},
    { name: 'address_3',                           type: 'string'},
    { name: 'title',                               type: 'string'},
    { name: 'lat',                                 type: 'int'},
    { name: 'lng',                                 type: 'int'},
    { name: 'percentage_discount',                 type: 'int'},
    { name: 'amount_paid',                         type: 'string'}
  ]
});